import { existsSync, mkdirSync, chmodSync, unlinkSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { execSync } from "node:child_process";
import { ClaudeMultiError, ErrorCode } from "@/errors";
import { detectPackageManager } from "@/util/runtime";
import { PINNED_CLAUDE_BIN } from "@/paths";

export interface WrapperOptions {
  name: string;
  configDir: string;
  binaryPath: string;
}

/**
 * Gets the path to the claude binary for wrapper scripts.
 *
 * Priority:
 *  1. CLAUDE_MULTI_CLAUDE_PATH env var (explicit override)
 *  2. [SAFE PARK] Pinned install at ~/.claude-multi/bin (managed by claude-multi)
 *  3. Global install in PATH
 */
export function getClaudePath(): string {
  // 1. Allow explicit override via env var
  const override = process.env.CLAUDE_MULTI_CLAUDE_PATH;
  if (override) {
    const resolved = resolve(override);
    if (!existsSync(resolved)) {
      throw new ClaudeMultiError(
        ErrorCode.CLAUDE_NOT_FOUND,
        `CLAUDE_MULTI_CLAUDE_PATH points to ${resolved} but that file does not exist`,
      );
    }
    return resolved;
  }

  // 2. Check pinned local install
  if (existsSync(PINNED_CLAUDE_BIN)) {
    return PINNED_CLAUDE_BIN;
  }

  // 3. Fall back to global PATH
  try {
    const command =
      process.platform === "win32" ? "where claude" : "which claude";
    const claudePath = execSync(command, { encoding: "utf-8" }).trim();
    const firstPath = claudePath.split("\n")[0];
    if (!firstPath) {
      throw new ClaudeMultiError(ErrorCode.CLAUDE_NOT_FOUND, "Could not determine Claude path");
    }
    return firstPath.trim();
  } catch (err) {
    if (err instanceof ClaudeMultiError) throw err;
    throw new ClaudeMultiError(ErrorCode.CLAUDE_NOT_FOUND, "Claude Code is not installed. Please install @anthropic-ai/claude-code first.", { cause: err });
  }
}

/**
 * Safe variant of getClaudePath() that returns null instead of throwing.
 */
export function tryGetClaudePath(): string | null {
  try {
    return getClaudePath();
  } catch {
    return null;
  }
}

/**
 * Generates the expected wrapper content for an instance (non-throwing).
 * Returns null if the Claude binary cannot be resolved.
 */
export function generateWrapperScriptSafe(options: WrapperOptions): string | null {
  const claudePath = tryGetClaudePath();
  if (!claudePath) return null;
  return buildWrapperScript(options, claudePath);
}

/**
 * Generates a wrapper script that sets CLAUDE_CONFIG_DIR
 */
export function generateWrapperScript(options: WrapperOptions): string {
  const claudePath = getClaudePath();
  return buildWrapperScript(options, claudePath);
}

export function buildWrapperScript(options: WrapperOptions, claudePath: string): string {
  return `#!/bin/sh
# Claude Multi - Wrapper for ${options.name}
# Generated by claude-multi
export CLAUDE_CONFIG_DIR="${options.configDir}"
exec "${claudePath}" "$@"
`;
}

/**
 * Generates a Windows batch wrapper script that sets CLAUDE_CONFIG_DIR
 */
export function generateWindowsWrapperScript(options: WrapperOptions): string {
  const claudePath = getClaudePath();

  return `@echo off
REM Claude Multi - Wrapper for ${options.name}
REM Generated by claude-multi

set "CLAUDE_CONFIG_DIR=${options.configDir}"
"${claudePath}" %*
`;
}

/**
 * Creates a wrapper script at the specified path
 */
export async function createWrapper(options: WrapperOptions): Promise<void> {
  const { binaryPath, configDir } = options;

  // Ensure the binary directory exists
  const binDir = dirname(binaryPath);
  if (!existsSync(binDir)) {
    mkdirSync(binDir, { recursive: true });
  }

  // Ensure the config directory exists
  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  // Generate and write the wrapper script
  if (process.platform === "win32") {
    // On Windows, create a .cmd batch file
    const script = generateWindowsWrapperScript(options);
    await writeFile(binaryPath, script);
  } else {
    // On Unix-like systems, create a Bun script
    const script = generateWrapperScript(options);
    await writeFile(binaryPath, script, { mode: 0o755 });
    // Ensure the script is executable
    chmodSync(binaryPath, 0o755);
  }
}

/**
 * Removes a wrapper script
 */
export function removeWrapper(binaryPath: string): void {
  if (existsSync(binaryPath)) {
    unlinkSync(binaryPath);
  }
}

/**
 * Gets the default binary path for a given instance name
 * Uses ~/.local/bin on Unix-like systems (user-writable, no sudo needed)
 * Uses the active package manager's global bin dir on Windows
 */
export function getDefaultBinaryPath(name: string): string {
  let binDir: string;

  if (process.platform === "win32") {
    const pm = detectPackageManager();
    const home = process.env.USERPROFILE || process.env.HOME || "";
    const appData = process.env.APPDATA || "";
    const windowsBinDirs: Record<typeof pm, string> = {
      bun: resolve(home, ".bun", "bin"),
      deno: resolve(home, ".deno", "bin"),
      npm: resolve(appData, "npm"),
      pnpm: resolve(appData, "npm"),
    };
    binDir = windowsBinDirs[pm];
  } else {
    binDir = resolve(process.env.HOME || "", ".local", "bin");
  }

  const binaryName =
    process.platform === "win32" ? `claude-${name}.cmd` : `claude-${name}`;
  return resolve(binDir, binaryName);
}
