import { existsSync, mkdirSync, chmodSync, unlinkSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { execSync } from "node:child_process";
import { ClaudeMultiError, ErrorCode } from "@/errors";
import { detectPackageManager } from "@/util/runtime";

export interface WrapperOptions {
  name: string;
  configDir: string;
  binaryPath: string;
}

/** Priority: CLAUDE_MULTI_CLAUDE_PATH env override, then global PATH lookup. */
export function getClaudePath(): string {
  const override = process.env.CLAUDE_MULTI_CLAUDE_PATH;
  if (override) {
    const resolved = resolve(override);
    if (!existsSync(resolved)) {
      throw new ClaudeMultiError(
        ErrorCode.CLAUDE_NOT_FOUND,
        `CLAUDE_MULTI_CLAUDE_PATH points to ${resolved} but that file does not exist`,
      );
    }
    return resolved;
  }

  try {
    const command = process.platform === "win32" ? "where claude" : "which claude";
    const claudePath = execSync(command, { encoding: "utf-8" }).trim();
    const firstPath = claudePath.split(/\r?\n/)[0];
    if (!firstPath) {
      throw new ClaudeMultiError(ErrorCode.CLAUDE_NOT_FOUND, "Could not determine Claude path");
    }
    return firstPath.trim();
  } catch (err) {
    if (err instanceof ClaudeMultiError) throw err;
    throw new ClaudeMultiError(
      ErrorCode.CLAUDE_NOT_FOUND,
      "Claude Code is not installed. Please install @anthropic-ai/claude-code first.",
      { cause: err },
    );
  }
}

export function tryGetClaudePath(): string | null {
  try {
    return getClaudePath();
  } catch {
    return null;
  }
}

export function generateWrapperScriptSafe(options: WrapperOptions): string | null {
  const claudePath = tryGetClaudePath();
  if (!claudePath) return null;
  return buildWrapperScript(options, claudePath);
}

export function generateWrapperScript(options: WrapperOptions): string {
  const claudePath = getClaudePath();
  return buildWrapperScript(options, claudePath);
}

export function buildWrapperScript(options: WrapperOptions, claudePath: string): string {
  return `#!/bin/sh
# Claude Multi - Wrapper for ${options.name}
# Generated by claude-multi
export CLAUDE_CONFIG_DIR="${options.configDir}"
exec "${claudePath}" "$@"
`;
}

export function generateWindowsWrapperScript(options: WrapperOptions): string {
  const claudePath = getClaudePath();

  return `@echo off
REM Claude Multi - Wrapper for ${options.name}
REM Generated by claude-multi

set "CLAUDE_CONFIG_DIR=${options.configDir}"
"${claudePath}" %*
`;
}

export async function createWrapper(options: WrapperOptions): Promise<void> {
  const { binaryPath, configDir } = options;

  const binDir = dirname(binaryPath);
  if (!existsSync(binDir)) {
    mkdirSync(binDir, { recursive: true });
  }

  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  if (process.platform === "win32") {
    const script = generateWindowsWrapperScript(options);
    await writeFile(binaryPath, script);
  } else {
    const script = generateWrapperScript(options);
    await writeFile(binaryPath, script, { mode: 0o755 });
    chmodSync(binaryPath, 0o755);
  }
}

export function removeWrapper(binaryPath: string): void {
  if (existsSync(binaryPath)) {
    unlinkSync(binaryPath);
  }
}

/** ~/.local/bin on Unix (user-writable, no sudo); package-manager global bin dir on Windows. */
export function getDefaultBinaryPath(name: string): string {
  let binDir: string;

  if (process.platform === "win32") {
    const pm = detectPackageManager();
    const home = process.env.USERPROFILE || process.env.HOME || "";
    const appData = process.env.APPDATA || "";
    const windowsBinDirs: Record<typeof pm, string> = {
      bun: resolve(home, ".bun", "bin"),
      deno: resolve(home, ".deno", "bin"),
      npm: resolve(appData, "npm"),
      pnpm: resolve(appData, "npm"),
    };
    binDir = windowsBinDirs[pm];
  } else {
    binDir = resolve(process.env.HOME || "", ".local", "bin");
  }

  const binaryName = process.platform === "win32" ? `claude-${name}.cmd` : `claude-${name}`;
  return resolve(binDir, binaryName);
}
