import { existsSync, mkdirSync, chmodSync, unlinkSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { execSync } from "node:child_process";

export interface WrapperOptions {
  name: string;
  configDir: string;
  binaryPath: string;
}

/**
 * Gets the path to the original claude binary
 */
export function getClaudePath(): string {
  try {
    // Try to find claude in PATH
    const claudePath = execSync("which claude", { encoding: "utf-8" }).trim();
    return claudePath;
  } catch {
    throw new Error(
      "Claude Code is not installed. Please install @anthropic-ai/claude-code first."
    );
  }
}

/**
 * Generates a Node.js wrapper script that sets CLAUDE_CONFIG_DIR
 */
export function generateWrapperScript(options: WrapperOptions): string {
  const claudePath = getClaudePath();

  return `#!/usr/bin/env node

// Claude Multi - Wrapper for ${options.name}
// Generated by claude-multi

import { spawn } from 'child_process';

process.env.CLAUDE_CONFIG_DIR = "${options.configDir}";

// Execute the original Claude Code CLI with all arguments
const claude = spawn("${claudePath}", process.argv.slice(2), {
  stdio: 'inherit',
  env: process.env
});

claude.on('exit', (code) => {
  process.exit(code || 0);
});
`;
}

/**
 * Creates a wrapper script at the specified path
 */
export async function createWrapper(options: WrapperOptions): Promise<void> {
  const { binaryPath, configDir } = options;

  // Ensure the binary directory exists
  const binDir = dirname(binaryPath);
  if (!existsSync(binDir)) {
    mkdirSync(binDir, { recursive: true });
  }

  // Ensure the config directory exists
  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  // Generate and write the wrapper script
  const script = generateWrapperScript(options);
  await writeFile(binaryPath, script, { mode: 0o755 });

  // Ensure the script is executable
  chmodSync(binaryPath, 0o755);
}

/**
 * Removes a wrapper script
 */
export function removeWrapper(binaryPath: string): void {
  if (existsSync(binaryPath)) {
    unlinkSync(binaryPath);
  }
}

/**
 * Gets the default binary path for a given instance name
 * Uses /usr/local/bin on Unix-like systems
 */
export function getDefaultBinaryPath(name: string): string {
  const binDir = process.platform === "win32"
    ? resolve(process.env.APPDATA || "", "npm")
    : "/usr/local/bin";

  const binaryName = `claude-${name}`;
  return resolve(binDir, binaryName);
}
